CREATE TABLE IF NOT EXISTS users(name TEXT PRIMARY KEY, bal INTEGER NOT NULL DEFAULT 0 CHECK(bal>=0));
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, user TEXT NOT NULL, adm INTEGER NOT NULL DEFAULT 0, created INTEGER);
CREATE TABLE IF NOT EXISTS cases(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, price INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS items(id INTEGER PRIMARY KEY AUTOINCREMENT, case_id INTEGER NOT NULL, name TEXT NOT NULL, value INTEGER NOT NULL, w REAL NOT NULL);
CREATE TABLE IF NOT EXISTS inv(id INTEGER PRIMARY KEY AUTOINCREMENT, user TEXT NOT NULL, name TEXT NOT NULL, value INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS inv_user ON inv(user);
CREATE TABLE IF NOT EXISTS reqs(id INTEGER PRIMARY KEY AUTOINCREMENT, user TEXT NOT NULL, type TEXT NOT NULL, amount INTEGER DEFAULT 0, from_user TEXT, item_name TEXT, item_value INTEGER, status TEXT NOT NULL DEFAULT 'new', created INTEGER);
CREATE INDEX IF NOT EXISTS reqs_user ON reqs(user);
CREATE TABLE IF NOT EXISTS admins(name TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS settings(k TEXT PRIMARY KEY, v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rockets(id INTEGER PRIMARY KEY AUTOINCREMENT, user TEXT NOT NULL, bet INTEGER NOT NULL, crash REAL NOT NULL, t0 INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'active');
CREATE INDEX IF NOT EXISTS rockets_user ON rockets(user,status);
CREATE TABLE IF NOT EXISTS codes(username TEXT PRIMARY KEY, hash TEXT NOT NULL, exp INTEGER NOT NULL, tries INTEGER NOT NULL DEFAULT 0, sent INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS tg_users(username TEXT PRIMARY KEY, chat_id INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS deposits(id INTEGER PRIMARY KEY AUTOINCREMENT, user TEXT NOT NULL, amount INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'new', charge TEXT, created INTEGER);

INSERT OR IGNORE INTO users(name,bal) VALUES('gold',0);
INSERT OR IGNORE INTO cases(id,name,price) VALUES(1,'Начальный',10),(2,'Золотой',100);
INSERT OR IGNORE INTO items(id,case_id,name,value,w) VALUES
(1,1,'Ничего',0,50),(2,1,'5 ⭐',5,30),(3,1,'15 ⭐',15,15),(4,1,'50 ⭐',50,5),
(5,2,'20 ⭐',20,45),(6,2,'100 ⭐',100,30),(7,2,'200 ⭐',200,20),(8,2,'1000 ⭐',1000,5);
